CREATE TABLE TB_CLIENTES(
   CODCLIENTE           VARCHAR2(20) NULL,
   RUC                  NUMBER NULL,
   RAZON_SOCIAL         VARCHAR2(100) NULL,
   TELEFONO             NUMBER NULL,
   CONTACTO             VARCHAR2(100) NULL,
   CONSTRAINT "PK_TB_CLIENTES" PRIMARY KEY (CODCLIENTE)
   
); 


CREATE TABLE TB_SEDES(
   CODSEDE              VARCHAR2(20) NULL,
   CODCLIENTE           VARCHAR2(20) NULL,
   PAIS                 VARCHAR2(20) NULL,
   DEPARTAMENTO         VARCHAR2(20) NULL,
   DIRECCION            VARCHAR2(200) NULL,
   TELEFONO             NUMBER NULL,
   CONTACTO             VARCHAR2(100) NULL,
   CONSTRAINT "PK_TB_SEDES" PRIMARY KEY (CODSEDE)
); 